#!/usr/bin/env node
/**
 * Icon pipeline for the Font Awesome Solid (fa6-solid) set from Iconify.
 *
 * Usage:
 *   node scripts/icons.js                 # regenerate the registry from existing SVGs
 *   node scripts/icons.js house user gear # download these icons, then regenerate
 *
 * Source of truth: assets/icons/*.svg (downloaded from Iconify).
 * Generated output: src/components/Icon/icons.generated.ts
 *
 * The <Icon> component reads the generated registry. To add icons, pass their
 * Font Awesome Solid names (see https://icon-sets.iconify.design/fa6-solid/).
 */
const fs = require('fs');
const path = require('path');
const https = require('https');

const ROOT = path.resolve(__dirname, '..');
const ICONS_DIR = path.join(ROOT, 'assets', 'icons');
const OUT_FILE = path.join(ROOT, 'src', 'components', 'Icon', 'icons.generated.ts');
/**
 * Iconify cho phép lấy icon từ NHIỀU bộ. Mặc định là Font Awesome Solid; muốn bộ
 * khác thì viết `bo:ten` — ví dụ `meteocons:clear-day-fill`.
 *
 * Tên tệp lưu lại KHÔNG mang tiền tố bộ, mà thêm tiền tố ngắn do người gọi đặt
 * (xem `--as=`), vì `<Icon name="...">` tra theo tên tệp. Bộ thời tiết dùng tiền
 * tố `wx-` để nhìn là biết ngay nó không phải icon giao diện thường.
 */
const API = (name, set) => `https://api.iconify.design/${set || 'fa6-solid'}/${name}.svg`;

function download(spec) {
  // `bo:ten` → lấy từ bộ `bo`; `ten` → Font Awesome Solid. `bo:ten=tenluu` để
  // đổi tên tệp lưu (icon thời tiết lưu thành `wx-*`).
  const [source, saveAsRaw] = spec.split('=');
  const hasSet = source.includes(':');
  const set = hasSet ? source.split(':')[0] : null;
  const name = hasSet ? source.split(':')[1] : source;
  const saveAs = saveAsRaw || name;
  return new Promise((resolve, reject) => {
    https
      .get(API(name, set), res => {
        if (res.statusCode !== 200) {
          res.resume();
          return reject(new Error(`HTTP ${res.statusCode} for ${name}`));
        }
        let data = '';
        res.on('data', c => (data += c));
        res.on('end', () => {
          if (!data.includes('<svg')) return reject(new Error(`No SVG for ${name}`));
          fs.writeFileSync(path.join(ICONS_DIR, `${saveAs}.svg`), data);
          resolve(saveAs);
        });
      })
      .on('error', reject);
  });
}

/** Extract viewBox width/height and the inner markup (paths) from a raw SVG. */
function parseSvg(svg) {
  const vb = svg.match(/viewBox="([^"]+)"/);
  // viewBox = "minX minY width height" — skip the two origin values.
  const [, , w, h] = (vb ? vb[1] : '0 0 512 512').split(/\s+/).map(Number);
  const inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .trim();
  return { w: w || 512, h: h || 512, body: inner };
}

function generate() {
  const files = fs
    .readdirSync(ICONS_DIR)
    .filter(f => f.endsWith('.svg'))
    .sort();

  const entries = files.map(f => {
    const name = f.replace(/\.svg$/, '');
    const { w, h, body } = parseSvg(fs.readFileSync(path.join(ICONS_DIR, f), 'utf8'));
    return { name, w, h, body };
  });

  const lines = entries
    .map(e => `  '${e.name}': { w: ${e.w}, h: ${e.h}, body: ${JSON.stringify(e.body)} },`)
    .join('\n');

  const out = `/* AUTO-GENERATED by scripts/icons.js — do not edit by hand. */
/* Font Awesome Solid (fa6-solid) via Iconify. Source: assets/icons/*.svg */

export interface IconData {
  /** viewBox width */
  w: number;
  /** viewBox height */
  h: number;
  /** inner SVG markup (path elements, fill="currentColor") */
  body: string;
}

export const ICONS = {
${lines}
} as const;

export type IconName = keyof typeof ICONS;
`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, out);
  console.log(`Generated ${entries.length} icons -> ${path.relative(ROOT, OUT_FILE)}`);
}

async function main() {
  fs.mkdirSync(ICONS_DIR, { recursive: true });
  const names = process.argv.slice(2);
  for (const name of names) {
    try {
      await download(name);
      console.log(`downloaded ${name}`);
    } catch (e) {
      console.error(`FAILED ${name}: ${e.message}`);
    }
  }
  generate();
}

main();
